[package]
name = "zellij-toggler"
version = "0.1.0"
edition = "2021"

[dependencies]
zellij-tile = "0.43.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-constant = "0.1.0"
